/*
 * generated by Xtext
 */
package org.openhab.model.script.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.openhab.model.script.ui.internal.ScriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScriptActivator.getInstance().getInjector(ScriptActivator.ORG_OPENHAB_MODEL_SCRIPT_SCRIPT);
	}
	
}
