/*
* generated by Xtext
*/
package org.openhab.model.script.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openhab.model.script.services.ScriptGrammarAccess;

public class ScriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openhab.model.script.parser.antlr.internal.InternalScriptParser createParser(XtextTokenStream stream) {
		return new org.openhab.model.script.parser.antlr.internal.InternalScriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}
	
	public ScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
