/*
* generated by Xtext
*/
package org.openhab.model.persistence.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.openhab.model.persistence.services.PersistenceGrammarAccess;

public class PersistenceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PersistenceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.openhab.model.persistence.parser.antlr.internal.InternalPersistenceParser createParser(XtextTokenStream stream) {
		return new org.openhab.model.persistence.parser.antlr.internal.InternalPersistenceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PersistenceModel";
	}
	
	public PersistenceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PersistenceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
