/*
 * File Name : gw.h
 * Author : ram krishnan
 * Created : 10/21/2013
 */

#ifndef __GW_H__
#define __GW_H__


// Message type 0x0 is reserved for ACKs
#define LPWMN_GW_MSG_TYPE_NODE_CNT_REQ     0x1
#define LPWMN_GW_MSG_TYPE_NODE_LIST_REQ    0x3

#define LPWMN_GW_MSG_TYPE_GET_NODE_LAST_FATAL_ERR_ID  0x4

#define LPWMN_GW_MSG_TYPE_RELAY_TO_NODE    0x5
#define LPWMN_GW_MSG_TYPE_RELAY_FROM_NODE  0x6
#define LPWMN_GW_MSG_TYPE_KEEP_ALIVE_REQ   0x7
#define LPWMN_GW_MSG_TYPE_KEEP_ALIVE_RESP  0x8
#define LPWMN_GW_MSG_TYPE_PING_NODE_REQ    0x9
#define LPWMN_GW_MSG_TYPE_NODE_PING_RESP   0xa

#define LPWMN_GW_MSG_TYPE_REBOOT_COORD  0xb

#define LPWMN_GW_MSG_TYPE_NODE_RT_DISC_STS   0x10

#define LPWMN_GW_MSG_TYPE_PATH_DISC_REQ    0x13
#define LPWMN_GW_MSG_TYPE_PATH_DISC_RESP   0x14

#define LPWMN_GW_MSG_TYPE_NODE_TRAFFIC_STATS_REQ   0x18

#define LPWMN_GW_MSG_TYPE_RESET_NODE_TRAFFIC_STATS  0x1a

#define LPWMN_GW_MSG_TYPE_STOP_TRAFFIC_REQ   0x1e
#define LPWMN_GW_MSG_TYPE_START_TRAFFIC_REQ  0x1f


#define LPWMN_GW_MSG_TYPE_GET_COORD_STATS    0x20
#define LPWMN_GW_MSG_TYPE_RESET_COORD_STATS  0x21

#define LPWMN_GW_MSG_TYPE_STOP_NWK   0x30
#define LPWMN_GW_MSG_TYPE_START_NWK  0x31

#define LPWMN_GW_MSG_TYPE_ENABLE_NWK_JOINS  0x40
#define LPWMN_GW_MSG_TYPE_DISABLE_NWK_JOINS  0x41
#define LPWMN_GW_MSG_TYPE_GET_NWK_JOIN_CTRL_STATE  0x42
#define LPWMN_GW_MSG_TYPE_ADD_NODE_TO_WHITE_LIST  0x43
#define LPWMN_GW_MSG_TYPE_DEL_NODE_FROM_WHITE_LIST  0x44
#define LPWMN_GW_MSG_TYPE_DELETE_WHITE_LIST  0x45
#define LPWMN_GW_MSG_TYPE_GET_WHITE_LIST_ENTRY  0x46

#define LPWMN_GW_MSG_TYPE_ADD_NODE_TO_BLACK_LIST  0x47
#define LPWMN_GW_MSG_TYPE_DEL_NODE_FROM_BLACK_LIST  0x48
#define LPWMN_GW_MSG_TYPE_DELETE_BLACK_LIST  0x49


#define LPWMN_GW_MSG_TYPE_CFG_DROP_BCN_REQS  0x4a
#define LPWMN_GW_MSG_TYPE_CFG_ACCEPT_BCN_REQS  0x4b
#define LPWMN_GW_MSG_TYPE_GET_BCN_REQ_HANDLING_CFG  0x4c

#define LPWMN_GW_MSG_TYPE_GET_BLACK_LIST_ENTRY  0x4d

#define LPWMN_GW_MSG_TYPE_SET_NWK_ID          0x50
#define LPWMN_GW_MSG_TYPE_SET_RADIO_CHANNEL         0x51
#define LPWMN_GW_MSG_TYPE_SET_NWK_COORD_EXT_ADDR  0x52
#define LPWMN_GW_MSG_TYPE_SET_RADIO_TX_PWR        0x53
#define LPWMN_GW_MSG_TYPE_START_COORD             0x54
#define LPWMN_GW_MSG_TYPE_STOP_COORD              0x55


#define LPWMN_GW_MSG_TYPE_GET_NWK_ID          0x59
#define LPWMN_GW_MSG_TYPE_GET_NWK_CHANNEL         0x5a
#define LPWMN_GW_MSG_TYPE_GET_NWK_COORD_EXT_ADDR  0x5b
#define LPWMN_GW_MSG_TYPE_GET_RADIO_TX_PWR        0x5c
#define LPWMN_GW_MSG_TYPE_GET_RADIO_PART_NR       0x5d
#define LPWMN_GW_MSG_TYPE_GET_RADIO_FREQ_BAND     0x5e
#define LPWMN_GW_MSG_TYPE_GET_RADIO_CARRIER_FREQ  0x5f
#define LPWMN_GW_MSG_TYPE_GET_RADIO_BAUD_RATE     0x60
#define LPWMN_GW_MSG_TYPE_GET_RADIO_MOD_FMT       0x61

#define LPWMN_GW_MSG_TYPE_SET_WCT  0x70   // set wall clock time
#define LPWMN_GW_MSG_TYPE_GET_WCT  0x71   // get wall clock time

#define LPWMN_MSG_TYPE_GET_UP_TIME  0x80  // in seconds


#define LPWMN_GW_MSG_TYPE_COORD_LOG           0x90
#define LPWMN_GW_MSG_TYPE_ENABLE_COORD_LOG    0x91
#define LPWMN_GW_MSG_TYPE_DISABLE_COORD_LOG   0x92


#define LPMWN_GW_MSG_TYPE_GET_COORD_FREE_MEM_DESC_CNT   0x93

#define LPWMN_GW_MSG_TYPE_DEREG_NODE   0xa0

#define LPWMN_GW_MSG_TYPE_EVENT   0xb0

#define LPWMN_GW_MSG_TYPE_GET_COORD_SW_BUILD_DATE  0xc0
#define LPWMN_GW_MSG_TYPE_GET_COORD_SW_BUILD_TIME  0xc1


#define LPWMN_GW_MSG_TYPE_GET_COORD_ATTR_VAL  0xc8
#define LPWMN_GW_MSG_TYPE_SET_COORD_ATTR_VAL  0xc9

#define LPWMN_MSG_TYPE_GET_RT_NH_ON_COORD  0xd0

#define LPWMN_GW_MSG_TYPE_GET_COORD_UP_TIME  0xda

#define LPWMN_GW_MSG_TYPE_MON_CHANN  0xe8

// Events sent to host by the LPWMN coordinator
#define LPWMN_GW_EVT_TYPE_NODE_REG               0x1
#define LPWMN_GW_EVT_TYPE_LOCAL_RT_DISC_STARTED  0x2
#define LPWMN_GW_EVT_TYPE_SYS_BOOT               0x3
#define LPWMN_GW_EVT_TYPE_NODE_DEREG             0x4
#define LPWMN_GW_EVT_TYPE_LOCAL_RT_DISC_OVER     0x5
#define LPWMN_GW_EVT_TYPE_BCN_REQ_RCVD           0x6
#define LPWMN_GW_EVT_TYPE_MAC_CNFRM              0x7
#define LPWMN_GW_EVT_TYPE_PURGE_RT_TBL           0x8
#define LPWMN_GW_EVT_TYPE_RCVD_PKT_WITH_INV_SRC_ADDR   0x9
#define LPWMN_GW_EVT_TYPE_ASSOC_REQ_DROPPED      0xa
#define LPWMN_GW_EVT_TYPE_ASSOC_REQ_RCVD         0xb
#define LPWMN_GW_EVT_TYPE_PATH_DISC_STARTED      0xc
#define LPWMN_GW_EVT_TYPE_PATH_DISC_OVER         0xd
#define LPWMN_GW_EVT_TYPE_RCVD_RT_REQ_WITH_INV_SRC_ADDR   0xe

#define LPWMN_GW_EVT_ID_LEN  0x1

#define LPWMN_GW_NODE_CNT_RESP_PYLD_LEN  2
#define LPWMN_GW_MSG_NODE_IDX_FIELD_LEN  2
#define LPWMN_GW_MSG_RADIO_TX_PWR_FIELD_LEN  2
#define LPWMN_GW_MSG_RADIO_CHANN_FIELD_LEN  2
#define LPWMN_GW_MSG_RADIO_CARRIER_FREQ_FIELD_LEN  4
#define LPWMN_GW_MSG_RADIO_BAUD_RATE_FIELD_LEN  4
#define LPWMN_GW_MSG_NODE_DATA_PUSH_INTERVAL_FIELD_LEN  2

#define LPWMN_GW_STS_SUCCESS               0x0
#define LPWMN_GW_STS_INV_REQ               0x1
#define LPWMN_GW_STS_INV_PARAMS            0x2
#define LPWMN_GW_STS_PREV_REQ_IN_PROGRESS  0x3
#define LPWMN_GW_STS_NWK_STOPPED           0x4
#define LPWMN_GW_STS_NO_ROUTE_TO_NODE      0x5
#define LPWMN_GW_STS_INV_PYLD_LEN          0x6
#define LPWMN_GW_STS_INV_RADIO_TX_PWR_SET_POINT   0x7


#define LPWMN_MSG_RSSI_LEN  1
#define LPWMN_MSG_CORR_LQI_LEN  1 

#define LPWMN_MAC_SHORT_ADDR_LEN  2
#define LPWMN_MAC_EXT_ADDR_LEN  8
#define LPWMN_MAC_NODE_CAPABILITY_INFO_LEN  1

#define LPWMN_COORD_SHORT_ADDR  0x1
#define LPWMN_MAX_UNICAST_SHORT_ADDR  0x7fff
#define LPWMN_MIN_MULTICAST_SHORT_ADDR  0x8000
#define LPWMN_MAX_MULTICAST_SHORT_ADDR  0xfffe
#define LPWMN_BROADCAST_SHORT_ADDR  0xffff

#define LPWMN_MESH_LEVEL_BROADCAST_ADDR   0xfff0

#define GW_NODE_MAX_CHAN_CNT  32

#define EUI64_ADDR_LEN  8


#define NODE_CAP_DEV_TYPE_BIT_SHIFT_MSK           (1 << 1)
#define NODE_CAP_INFO_POWER_SOURCE_BIT_SHIFT_MSK  (1 << 2)
#define NODE_CAP_INFO_RX_ON_IDLE_BIT_SHIFT_MSK    (1 << 3)
#define NODE_CAP_INFO_SEC_CAP_BIT_SHIFT_MSK       (1 << 6)
#define NODE_CAP_INFO_ALLOC_ADDR_BIT_SHIFT_MSK    (1 << 7)


#define LPWMN_GW_PATH_DISC_EVT_HOP_CNT_FIELD_LEN  1
#define LPWMN_GW_PATH_DISC_EVT_STS_FIELD_LEN  1

typedef enum
{
   ADP_STS_SUCCESS,
   ADP_STS_NODE_NOT_FOUND,
   ADP_STS_OOM,
   ADP_STS_TX_FLR,
   ADP_STS_RT_DISC_OOM,
   ADP_STS_RT_DISC_FAILED,
   ADP_STS_ROUTING_LOOP,
   ADP_STS_MAX_HOPS_EXCEEDED,
   ADP_STS_NO_ROUTE,
   ADP_STS_PATH_DISC_TIMED_OUT,
   ADP_STS_NODE_NOT_ASSOCIATED,
   ADP_STS_TOO_MANY_FRAGMENTS ,
   ADP_STS_FRAG_NOT_SUPPORTED
} ADP_sts_t;

typedef struct _LPWMN_nodeListEntry_
{
   unsigned int shortAddr;
   unsigned char extAddr[LPWMN_MAC_EXT_ADDR_LEN];
   unsigned int msgRcvdCnt;
   unsigned int regCnt;

   struct _LPWMN_nodeListEntry_ *next_p;
} LPWMN_nodeListEntry_s;

#endif
