/*
 * File Name : node_attr.h
 * Author : ram krishnan
 * Created : april/22/2015
 */

#ifndef __NODE_ATTR_H__
#define __NODE_ATTR_H__

#define MAC_CCA_FLR_CNT_ATTR_ID   2
#define MAC_CSMA_FLR_CNT_ATTR_ID  3
#define MAC_ACK_TMO_CNT_ATTR_ID  4
#define MAC_CCA_OK_CNT_ATTR_ID  5
#define NM_MAC_ACK_TMO_DELTA_ATTR_ID  1
#define NM_MAC_TX_ON_CCA_ENA_FLAG_ATTR_ID  8
#define MAC_LPWMN_ID_ATTR_ID  9
#define PHY_RF_CHANN_ID_ATTR_ID  10
#define APP_SENSOR_DATA_PUSH_INTERVAL_SECS_ATTR_ID 11
#define FW_BUILD_DATE_ATTR_ID 12
#define FW_BUILD_TIME_ATTR_ID 13
#define SYS_FREE_MEM_DESC_CNT_ATTR_ID  14  
#define MAC_ACK_FRAME_RAW_TRX_TIME  15
#define FU_IMAGE_STORE_IMAGE_FLAGS_ATTR_ID  16
#define FU_IMAGE_STORE_IMAGE_INFO_ATTR_ID  17

#define FU_IMAGE_STORE_IMAGE_1_LEN_ATTR_ID  20
#define FU_IMAGE_STORE_IMAGE_1_SEG_CNT_ATTR_ID  21
#define FU_IMAGE_STORE_IMAGE_1_TYPE_ATTR_ID  22
#define FU_IMAGE_STORE_IMAGE_1_IMAGE_RCVD_TIME_STAMP_ATTR_ID  23

#define FU_IMAGE_STORE_IMAGE_2_LEN_ATTR_ID  40
#define FU_IMAGE_STORE_IMAGE_2_SEG_CNT_ATTR_ID  41
#define FU_IMAGE_STORE_IMAGE_2_TYPE_ATTR_ID  42
#define FU_IMAGE_STORE_IMAGE_2_IMAGE_RCVD_TIME_STAMP_ATTR_ID  43

#define NWK_ROUTING_TABLE_MAX_ENTRY_CNT_ATTR_ID  60
#define NWK_ROUTING_TABLE_VALID_ENTRY_CNT_ATTR_ID  61

#define NWK_ROUTING_TABLE_ENTRY_ATTR_ID  100

#define NWK_RT_DISC_STARTED_CNT_ATTR_ID  120
#define NWK_RT_DISC_SUCCESS_CNT_ATTR_ID  121
#define NWK_RT_DISC_FLR_CNT_ATTR_ID  122
#define NWK_RT_DISC_ERR_CNT_ATTR_ID  123

#define MESH_TRIGGER_PATH_DISC_ATTR_ID  600
#endif
