#!/bin/bash

ps -ef | grep -v grep | grep runner
if [ $? -eq 0 ]
then
  runner_pid=`ps -eo pid -eo comm | grep runn | cut -f1 -d'r'`
  #echo $?
  echo runner_pid $runner_pid 

  echo sudo kill -SIGCONT $runner_pid
  sudo kill -SIGCONT $runner_pid

  while [ 1 ] 
  do
    echo waiting for wsuart to be restarted
    sleep 1
    ps -ef | grep -v grep | grep wsuart
    if [ $? -eq 0 ] 
    then
      break
    fi
  done
else
  runner.sh is not currently running !!
fi  
