/*
 * generated by Xtext
 */
package org.openhab.model.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.openhab.model.ui.internal.SitemapActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SitemapExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SitemapActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SitemapActivator.getInstance().getInjector(SitemapActivator.ORG_OPENHAB_MODEL_SITEMAP);
	}
	
}
